---
title: Number DNA
timezone: America/New_York
collections:
  data-math-remediation:
    title: 'Data: Math Remediation'
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: 'This web page will convey information and progress reports concerning
  an ambitious web based project to help its users develop strong foundational numeracy
  skills.  With this strong foundation any one can successfully take on  successive
  levels of math training. The name of this project is numberDNA.

'
baseurl: 
url: 
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
