---
title: Number DNA
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Dan Neaton
email: 
github_username: 
twitter_username: 
description: "\n"
google_analytics: 
baseurl: 
url: 
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
