---
title: Number DNA
timezone: America/New_York
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
author: Dan Neaton
email: neatond@gmail.com
twitter_username: "@neatond"
description: Looking for investors to fund the development of Number DNA, a radically
  different online, user driven, basic math remediation project.
google_analytics: UA-109219110-1
baseurl: 
url: 
markdown: kramdown
theme: minima
gems:
- jekyll-feed
exclude:
- Gemfile
- Gemfile.lock
